version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - HOST_URL=${HOST_URL}
      - CACHE_DIR=/data/image_cache
    volumes:
      - image_cache:/data/image_cache
    restart: unless-stopped

volumes:
  image_cache:
