name: file-server
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi
    - uvicorn
    - python-dotenv
    - pydantic-settings
    - httpx 